name: Include image in image description issues

on:
  issues:
    types: [opened, edited]

jobs:
  comment:
    name: Post related image
    runs-on: ubuntu-latest

    steps:
      - name: Add comment with image
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_API_TOKEN }}
          script: |
            const { postImageComment } = await import("${{ github.workspace }}/.github/workflows/scripts/comments.mjs")

            await postImageComment({ github, context }, github.event.issue)
